apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    - hello
    - ${META_LABEL}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ${APP_LABEL}
    spec:
      containers:
        - name: nginxoxo
          image: nginx:1.7.9
          ports:
            - containerPort: ${PORT}
        - name: ${CONT_NAME}
          image: log-sidecar:0.1.1
          ports:
            - containerPort: 80
